### ISSUE TITLE
Change in v3 - clearing parameters from URL clears them from the state

### ISSUE THREAD

**Issue by CharlesRea** [Dean177/use-url-state#147]
If you're at `/wherever?animal=ant` and you navigate to `/wherever?`, in v3 you are given `{}` as the URL state - IE the value is completely removed from the state.

In v2, you'd still get a value in the state. It's happening just because of how `setState` no longer accepts `Partial<T>` anymore. In v2, React would just treat it as a partial state update so you'd get back the previous values.

I had started putting in a fix but realised it's not actually clear what the ideal behaviour is here. I think I'd actually expect to get nothing back from the state, ie the new behaviour is correct, but I can see arguments both ways.

I'm guessing this wasn't an intentional change - thoughts?

**Comment by CharlesRea** [comment]
And hopefully this is the last breaking change... it's

**Comment by Dean177** [comment]
This was an intentional change, I consider the old behvaior to be a bug, you had no way of clearing the state!

**Comment by Cosmo439** [comment]
I have been fighting this problem recently. Thank you for changing it, but to @CharlesRea s point, would it be possible to add a flag for the old way vs the new way?

**Comment by Cosmo439** [comment]
Any chance to get this ported to the v2 line? You changed over to using hooks exclusively in v3, and I'm not at a point where I can upgrade React in my project.

**Comment by Dean177** [comment]
Sure thing @Cosmo439, I would be up for accepting a pull-request if you fancy having a go ad adding a flag for the v2 branch.
