### ISSUE TITLE
Clear state from URL when empty/undefined/null

### ISSUE THREAD

**Issue by danielpost** [Dean177/use-url-state#165]
Is there a way to clear the state from the URL when it's empty? For example, in a project I'm currently working on the URL often ends up looking like `?archive=false&search=&month=` when I would like it to be just `?archive=false`. Is this possible using this library?

I'm using the beta version with the `useUrlState` hook.

**Comment by Dean177** [comment]
Hi @danielpost, thanks for pointing this out.

You can do this using custom serialisation  (which isn't documented at the moment)

```js
let [urlState, setUrlState] = useUrlState(
  { archive: false, search: null },
  { 
    serialisation: {
      parse: (url) => qs.parse(url, { ignoreQueryPrefix: true }),
      stringify: (state) => {
        let displayState = {}
        for(let key in state) {
          if (state[key] != null) {
            displayState[key] = state[key]
          }
        }
        return qs.stringify(displayState, { addQueryPrefix: true })
      },
    }
  }
)
```
      
With that configuration if you explicitly set values to null they won't be displayed in the url.

If that solves your problem and the example makes sense I will document it and add it to the readme.

**Comment by danielpost** [comment]
Hi Dean, thanks for your answer! It worked for me using the [query-string](https://github.com/sindresorhus/query-string) package.

What would you need for the documentation?

**Comment by Dean177** [comment]
I am adding a “recepies” section to the 3.0.0 branch so it could go there with a sentence or two explaining why you might want it
